Name:           python3-skyfield
Version:        1.54
Release:        2%{?dist}
Summary:        Elegant astronomy for Python

License:        MIT
URL:            https://github.com/skyfielders/python-skyfield
Source0:        https://files.pythonhosted.org/packages/source/s/skyfield/skyfield-%{version}.tar.gz#/%{name}-%{version}.tar.gz

BuildArch:      noarch

BuildRequires:  python3-devel
BuildRequires:  python3-pip
BuildRequires:  python3-setuptools
BuildRequires:  python3-wheel

Requires:       python3-astropy
Requires:       python3-certifi
Requires:       python3-jplephem
Requires:       python3-pandas
Requires:       python3-sgp4
Requires:       python3-sympy

%description
Skyfield computes positions for the stars, planets, and satellites in orbit around the Earth.
Its results should agree with the positions generated by the United States Naval Observatory and their Astronomical Almanac to within 0.0005 arcseconds (half a “mas” or milliarcsecond).
- Written in pure Python.
- Installs without any compilation.
- Supports Python 2.7 and Python 3.


%prep
%autosetup -n skyfield-%{version}

%build
%pyproject_wheel

%install
%pyproject_install
%pyproject_save_files skyfield

%files -n python3-skyfield -f %{pyproject_files}
%license LICENSE
%doc README.rst

%changelog
* Mon Apr 13 2026 Deuchnord <jerome@deuchnord.fr> - 1.54
- Initial package for Fedora/COPR
